"""Code generator (mocked for V0.1)."""

from dataclasses import dataclass
from typing import Dict, List
from daedalus.planner import ImplementationPlan


@dataclass
class CodeProposal:
    """Code proposal (mocked)."""
    task_id: str
    files: Dict[str, str]  # filename -> code content
    status: str = "GENERATED"
    
    def summary(self) -> str:
        return f"Code proposal: {len(self.files)} files, {sum(len(c) for c in self.files.values())} LOC"


def generate_code(plan: ImplementationPlan) -> CodeProposal:
    """Generate code from plan (mocked)."""
    files = {}
    
    # Create placeholder files
    for fname in plan.files_to_create:
        files[fname] = f'''"""
Auto-generated by Daedalus V0.1

Task: TASK-{plan.task_id}
Title: {plan.title}
"""

# Implementation placeholder
# This would contain real code in V1

__all__ = []
'''
    
    for fname in plan.files_to_modify:
        files[fname] = f'''# Modified by Daedalus V0.1 for TASK-{plan.task_id}
# See decision log for details
'''
    
    return CodeProposal(
        task_id=plan.task_id,
        files=files,
        status="GENERATED"
    )
